### ISSUE TITLE
[Cloud] Kubernetes Controller 개발 환경 구축

### ISSUE THREAD

**Issue by wonjong-yoo** [sortteam/HyKuFe#7]
**제목**
- 기능 설명
custom controller 개발을 위한 operator-sdk 개발환경 설치입니다.

Custom Resource Definition(CRD)는 operator-sdk CLI를 사용하여 생성할 수 있습니다.
EX)
`$ operator-sdk add api --api-version=cache.example.com/v1alpha1 --kind=Memcached`

만든 CRD를 감시하고 컨트롤하는 Controller는 똑같이 operator-sdk CLI를 사용하여 생성할 수 있습니다.
`$ operator-sdk add controller --api-version-cache.example.com/v1alpha1 --kind=Memcached`

Controller는 CRD를 감시하며 변경이 일어난 경우 Controller내의 Reconcile 메서드에 해당 CRD의 Name과 Namespace를 Reconcile.Request 타입으로 포장하여 호출합니다. 

우리가 할 일은 Reconcile 메서드에서 CRD의 현재 상태를 Desired 상태로 바꾸는 작업을 하는 것입니다.

/pkg/apis/.../[이름]_type.go 에 정의합니다.
- 상세한 아키텍쳐 설명

**개발 버전**
 - OS:

**commit hash**

**Additional context**
## 설치 및 세팅

1. Operator SDK CLI를 설치한다.

[operator-framework/operator-sdk](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/install-operator-sdk.md)

2. 프로젝트 생성

    # Create an app-operator project that defines the App CR.
    $ mkdir -p $HOME/projects/example-inc/
    # Create a new app-operator project
    $ cd $HOME/projects/example-inc/
    $ export GO111MODULE=on
    
    # 프로젝트 생성, repo는 무시하면 기본 템플릿으로 생성된다.
    $ operator-sdk new app-operator --repo github.com/example-inc/app-operator

# SDK 구조 설명

---

## Manager

Operator (`cmd/manager/main.go`)에서 메인 프로그램은 Manager를 초기화하고 실행한다.

[Package manager](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/manager#Manager)

Manager는 `pkg/apis/...` 아래의 정의된 모든 커스텀 리소스를 등록하고 `pkg/controller/...` 아래의 모든 컨트롤러를 실행한다. 

Manager는 모든 컨트롤러가 리소스에 대한 감시해야할 namespace를 제한할 수 있다.

    mgr, err := manager.New(cfg, manager.Options{Namespace: namespace})

기본값으로 Operator가 동작하고 있는 네임스페이스가 될것이다. 모든 namespace를 감시해기 위해선 namespace option을 비워야한다.

## 새로운 Custom Resource Definition 추가하기

Memchaced Kind와 [cache.exmaple.com/v1alpha1](http://cache.exmaple.com/v1alpha1) API Version을 가지는 CRD를 추가하자.

    $ operator-sdk add api --api-version=cache.example.com/v1alpha1 --kind=Memcached

`pkg/apis/cache/v1alpah1/...` 아래에 Memcached Rresource API를 스캐폴드할것이다.

### Define the spec and status

`Memcached` Custom Resource의 상태와 spec을 수정해보자.

    type MemcachedSpec struct {
    	// Size is the size of the memcached deployment
    	Size int32 `json:"size"`
    }
    type MemcachedStatus struct {
    	// Nodes are the names of the memcached pods
    	Nodes []string `json:"nodes"`
    }

`*_types.go` 파일을 수정한 후에 항상 아래 커맨드를 호출해서 리소스 타입에 대한 생성 코드를 업데이터 해야한다.

    $ operator-sdk generate k8s

### OpenAPI validation

deploy/crds/caches_v1alpha1_memcached_crd.yaml CRD에서 OpenAPI validation 부분을 업데이트하기 위해서 아래와 같은 커맨드를 실행한다.

    $ operator-sdk generate openapi

validation section은 Memcached Custom Resource가 생성되거나 업데이트 될때 쿠버네티스가 프로퍼티들이 적절하게 설정되었는지 검사하게 해준다. 예제에서 생성된 YAML은 다음과 같다.

    spec:
      validation:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                size:
                  format: int32
                  type: integer

OpenAPI 3.0 validation schema에 대해서 더 알고싶다면 아래를 참고해라.

[Extend the Kubernetes API with CustomResourceDefinitions](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#specifying-a-structural-schema)

## Add a new Controller

---

 Memcached resource를 감시하고 reconcile할 수 있는 새로운 컨트롤러를 프로젝트에 추가해보자.

    $ operator-sdk add controller --api-version-cache.example.com/v1alpha1 --kind=Memcached

위 커맨드를 실행하면 `pkg/controller/memcached/...` 아래에 새로운 컨트롤러 구현이 scaffold 될것이다.

예제 컨트롤러는 각 `Memcached` CR spec에 대해서 아래와 같은 reconciliation 로직을 실행한다.

- 만약 존재하지 않으면 Memcached Deployment를 생성한다.
- Deployment 크기를 Memcached CP spec에 기술한것과 같은 크기로 되는 것을 보장한다.
- status writer를 사용하여 Memcached pods의 이름과 status writer를 이용하여 Memcached CP를 업데이트 한다.

다음 두 섹션에서 어떻게 컨트롤러가 리소스를 감시하고 어떻게 reconcile loop가 트리거되는지 살펴보겠다. 

## Resources watched by the Controller

`pkg/controller/memcached/memcached_controller.go` 에서 어떻게 컨틀롤러가 리소스를 감시하는지 컨트롤러 구현을 분석해보자.

주요 리소스로써 Memcached 타입에 대해서 먼저 보자. reconcile loop에서 Add/Update/Delete 이벤트는 reconcile Request로 보내질 것이다.(?)

    err := c.Watch(
      &source.Kind{Type: &cachev1alpha1.Memcached{}}, &handler.EnqueueRequestForObject{})

Deployments에 대한 다음 감시는 이벤트 핸들러가 각 이벤트에 대한 reconcile `Request` 를 매핑할 것이다.(?) The next watch is for Deployments but the event handler will map each event to a reconcile Request for the owner of the Deployment.

이러한 케이스는 Deployment가 생성된 Memcached object이다. 이것은 컨트롤ㄹ러가 Deployment를 secondary resource로써 감시할 수 있도록 한다.

    err := c.Watch(&source.Kind{Type: &appsv1.Deployment{}}, &handler.EnqueueRequestForOwner{
        IsController: true,
        OwnerType:    &cachev1alpha1.Memcached{},
      })

### Controller Configurations

컨트롤러를 초기화할때나 감시 파라미터를 선언할 때 사용할 수 있는 몇가지 유용한 설정들이 있다. 더 자세하게 알고싶다면 아래를 참고.

[Package controller](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/controller)

- `MaxConcurrentReconciles` 옵션을 통해 컨트롤러에 대한 현재 Reconciles의 최대 개수를 설정한다. 기본값은 1이다.

        _, err := controller.New("memcached-controller", mgr, controller.Options{
            MaxConcurrentReconciles: 2,
            ...
        })

- [predicates](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/event-filtering.md)를 사용하여 감시 이벤트를 필터링한다.
- reconcile loop에서 어떻게 감시 이벤트가 reconcile requests로 번역할것인지를 바꾸는 EventHandler의 타입을 선택한다. primary와 secondary resources에 비해서 operator 관계가 더 복잡한 경우 다음과 같이 한다. `EnqueueRequestsFromMapFunc` 핸들러는 감시 이벤트를 임의의 reconcile requests 집합으로 변환할 때 쓰일 수 있다.

### Reconcile loop

모든 컨트롤러는 reconcile loop를 구현한 Reconcile() 메서드를 가지고 있는 Reconciler Object가 있다. reconcile loop는 primary resource object, memcached 등을 조회할 때 쓰이는 Namespace/Name key인 `Request` argument를 받는다.

    func (r *ReconcileMemcached) Reconcile(request reconcile.Request) (reconcile.Result, error) {
      // Lookup the Memcached instance for this reconcile request
      memcached := &cachev1alpha1.Memcached{}
      err := r.client.Get(context.TODO(), request.NamespacedName, memcached)
      ...
    }

return values에 기반으로 `Result`와 에러, `Request` 는 다시 큐에 들어갈것이고 reconcile lop는 다시 트리거될 것이다. ?

→ 리턴 값에 따라서 큐에 다시 들어갈지 안들어갈지 판단하는듯.

    // Reconcile successful - don't requeue
    return reconcile.Result{}, nil
    // Reconcile failed due to error - requeue
    return reconcile.Result{}, err
    // Requeue for any reason other than error
    return reconcile.Result{Requeue: true}, nil

`Result.RequeueAfter`을 설정하여 특정 주기로 `Request` 를 다시 큐에 넣을 수 있다.

    import "time"
    
    // Reconcile for any reason than error after 5 seconds
    return reconcile.Result{RequeueAfter: time.Second*5}, nil

## Build and run the operator

---

operator를 실행하기 전에 CRD는 반드시 쿠버네티스 apiserver에 등록되어야 한다.

    $ kubectl create -f deploy/crds/cache_v1alpha1_memcached_crd.yaml

이것이 끝나면 operator를 실행시킬 두가지 방법이 있다.

- 쿠버네티스 클러스터 내에서 Deployments에서
- 클러스터 바깥쪽에서 Go 프로그램에서

### 1. Run as a Deployment inside the cluster

**Note:** `operator-sdk build`는 기본으로 `docker build`를 호출하고 옵션으로 `buildah bud`를 호출한다. 만약 `buildah`를 사용하고 있다면 `operator-sdk build`를 호출하는 것을 생략할 수 있다. 만약 도커를 사용하고 있다면 도커 데몬이 실행하고 있는지 확인해야하며 당신은 sudo  없이 도커 클라이언트를 실행할 수 있다. 도커가 문제 없이 실행하고 있는지 검사하고 충분한 권한이 있는지 봐라.

**Note:** 만약 `go.mod`파일이 존재하고 vendor/ 디렉토리가 있다면 아래 명령어를 실행해라.

    $ go mod vendor

(go.mod 파일에 있는 의존성을 vendor/ 디렉토리에 다운로드 해주는듯.)

[Go Modules 시작하기](https://aidanbae.github.io/code/golang/modules/)

memcached-operator 이미지를 빌드하고 저장소에 보내자.

    $ operator-sdk build quay.io/example/memcached-operator:v0.0.1
    $ sed -i 's|REPLACE_IMAGE|quay.io/example/memcached-operator:v0.0.1|g' deploy/operator.yaml
    $ docker push quay.io/example/memcached-operator:v0.0.1

Deployment 정의가 `deploy/operator.yaml`에 생성되었다. 

RBAC를 설치하고 memcached-operator를 배포하자.

    $ kubectl create -f deploy/service_account.yaml
    $ kubectl create -f deploy/role.yaml
    $ kubectl create -f deploy/role_binding.yaml
    $ kubectl create -f deploy/operator.yaml

### 2. Run locally outside the cluster

이 방법은 개발 단계에서 배포와 테스트를 더 빠르게 할때 권장한다.

operator의 이름을 환경변수에 설정하자.

    $ export OPERATOR_NAME=memcached-operator

opreator 기본 쿠버네티스 설정 파일과 함께 로컬에서 실행한다.

    $ operator-sdk up local --namespace=default
    2018/09/30 23:10:11 Go Version: go1.10.2
    2018/09/30 23:10:11 Go OS/Arch: darwin/amd64
    2018/09/30 23:10:11 operator-sdk Version: 0.0.6+git
    2018/09/30 23:10:12 Registering Components.
    2018/09/30 23:10:12 Starting the Cmd.

`--kubeconfig=<path/to/kubeconfig>` flag를 통해서 특정 kubeconfig를 지정할 수 있다.

### Adding 3rd party Resources To your operator

operator에 Manager는 client-go scheme package 내에서 찾을 수 있는 기본 쿠버네티스 리소스 타입만 지원하고 `pkg/apis` 아래에 정의된 모든 커스텀 리소스 타입의 schemes들이 등록될 것이다. 

    import (
      "github.com/example-inc/memcached-operator/pkg/apis"
      ...
    )
    
    // Setup Scheme for all resources
    if err := apis.AddToScheme(mgr.GetScheme()); err != nil {
      log.Error(err, "")
      os.Exit(1)
    }

operator에 3rd party 리소스를 추가하기 위해서는 반드시 Mnagers's Scheme을추가해야한다. `AddToScheme()` 메서드를 생성하거나 당신의 scheme에 쉽게 리소스를 추가할 수 있는 것을 재사용. 예제는 너가 함수를 정의하고 schemeBuilder를 생성하는 런타임 패키지를 사용하는 것을 보여준다.

[kubernetes/api](https://github.com/kubernetes/api/blob/master/apps/v1/register.go#L41)

**Comment by wonjong-yoo** [comment]
```
Unexpected end of /proc/mounts line `overlay / overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/MAGTWEGYEWGMYR67AQMXBD365A:/var/lib/docker/overlay2/l/YDPHW3INGI6NPIVKUUZ7YWNWTH:/var/lib/docker/overlay2/l/NOOMXPW3U6S3FT5EKYVCHBYGCV:/var/lib/docker/overlay2/l/6T5GI7FO2KEHOTEES7RT235DCA:/var/lib/docker/overlay2/l/CKLZOYLLIMK6KOSJLUN4QFNC23:/var/lib/docker/overlay2/l/MG5OXNXVCSRD5MJJ7XNUHW5GKN:/var/lib/docker/overlay2/l/GHGG2VSK3RYWNGHCQF46TWWZPC:/var/lib/docker/overlay2/l/N5VYNQEBJ6DMTRQRSSRMLPN7LF:/var/lib/docker/overlay2/l/CO7DXH34GDZ4D'
Unexpected end of /proc/mounts line `EA3JOB3TA3XDY:/var/lib/docker/overlay2/l/QE7W3T3QGVZTIFYYUNSHRPGHS6:/var/lib/docker/overlay2/l/JDCFPATQBYT55SK6XAWAUIUZLK:/var/lib/docker/overlay2/l/OLU44U7ZVN55JXWR4VFMCGV2H6:/var/lib/docker/overlay2/l/TM53J54TTEQEXYGDZYD7EAHITA:/var/lib/docker/overlay2/l/PFA32JOJEVT5PJ6Z5TACVOBEBE:/var/lib/docker/overlay2/l/MWW545WYTPAQTNEN6QO4EWNDGF:/var/lib/docker/overlay2/l/5MLWELDTGBWCR2I6HV34NRRI3M,upperdir=/var/lib/docker/overlay2/bf45cdc9f15e83cf138a5489ead71a913e73c32b87565d1b978ff5692212d745/diff,workdir=/var/li'
Warning: Permanently added 'horovod-job-example-volcanojob-worker-1.horovod-job-example-volcanojob,10.233.120.5' (ECDSA) to the list of known hosts.
Warning: Permanently added 'horovod-job-example-volcanojob-worker-0.horovod-job-example-volcanojob,10.233.96.8' (ECDSA) to the list of known hosts.
Unexpected end of /proc/mounts line `overlay / overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/VYBUHAJA6ZPQU62S37SOXRKQAK:/var/lib/docker/overlay2/l/W7XVCJBWS2DUFE2HOENOFITDFI:/var/lib/docker/overlay2/l/WB6FQKGZUNKLWKK77ZUSC2PCES:/var/lib/docker/overlay2/l/2RJCPXFZCAOPGONNVR2VEXINFR:/var/lib/docker/overlay2/l/4YT3TU5KVWCYFAGVY6NONQDJQP:/var/lib/docker/overlay2/l/IYTYXFU3HPB4CMWGYUZJHC5AFI:/var/lib/docker/overlay2/l/MCNY3UBYNELWRAQUJUTYMGULPR:/var/lib/docker/overlay2/l/RC3SHHQYES5VU74E4ZM43RNK36:/var/lib/docker/overlay2/l/25POBMBIHM2ZR'
Unexpected end of /proc/mounts line `HVS5CGHBJF6VU:/var/lib/docker/overlay2/l/XYO4QKMQDNHES37UMLBPH4A7ZC:/var/lib/docker/overlay2/l/MXDEVTB7Z2I73R77CV3RDR5QS7:/var/lib/docker/overlay2/l/PBXC5YHVI5RSF2DCFMSIPNGFSY:/var/lib/docker/overlay2/l/YJZF5QJMY5S354VP4AM6C4OMCD:/var/lib/docker/overlay2/l/BBUX6ENND3XQN3EQN4D6A75LXR:/var/lib/docker/overlay2/l/DP5RYP44NVCBQHJOW46QW5VU5L:/var/lib/docker/overlay2/l/SVGV6VVJKHWET4K5DLKYJEUX6H,upperdir=/var/lib/docker/overlay2/48cbd689883cf5a975677ae2b615460035f6fc1e5e59a96eb718a47e0bd8c128/diff,workdir=/var/li'
Unexpected end of /proc/mounts line `overlay / overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/425YGS7AXWKNZCCWCR2RXRBJOL:/var/lib/docker/overlay2/l/YJL7HREAKFYFJW6J55KMLGU32L:/var/lib/docker/overlay2/l/O6OFGZNRJPT5ZG2GRHX4G4G4L5:/var/lib/docker/overlay2/l/FXM6JKX4EZHB5I3C6INGMVPLOQ:/var/lib/docker/overlay2/l/TMNA5IPCCFYBLAD6IKBDDOIVFB:/var/lib/docker/overlay2/l/3E2WRUF75JTGV22UGXPG3SSAWH:/var/lib/docker/overlay2/l/EXC3HQM5MIH74ALS5SRQQXL6OF:/var/lib/docker/overlay2/l/QNHDM3VTH6GSQ4YVWMNWPRIUQC:/var/lib/docker/overlay2/l/YU2X5BX7PHLRD'
Unexpected end of /proc/mounts line `HSWWGBY4W7XB5:/var/lib/docker/overlay2/l/V3AUPZMWCWDMPJLBJBROODRLXD:/var/lib/docker/overlay2/l/HM54XER43FW72CIU7SBMEDYCDN:/var/lib/docker/overlay2/l/QYHFL27CP7KPRH3E7BXVLRTMAL:/var/lib/docker/overlay2/l/2OGNKFQQSC6WQYX7ULEPRHAMGB:/var/lib/docker/overlay2/l/BSLLTSNER652P5YXURRPWBBRVM:/var/lib/docker/overlay2/l/BMOTEODN2PYVABX7UPVEQRYX7G:/var/lib/docker/overlay2/l/QFGAVSDYG7AZYNTHUGHS2WIAOG,upperdir=/var/lib/docker/overlay2/e322e6e3e5fe4a153553b76d3a91a688cd6346c6db55cceeb4ca5800f815d206/diff,workdir=/var/li'
INFO:tensorflow:here we go
--------------------------------------------------------------------------
[[57994,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: horovod-job-example-volcanojob-worker-0

Another transport will be used instead, although this may result in
lower performance.
--------------------------------------------------------------------------
INFO:tensorflow:here we go
INFO:tensorflow:program start at 1568826983.920318
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:program start at 1568826984.312800
INFO:tensorflow:Graph was finalized.
2019-09-18 17:16:24.591858: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
INFO:tensorflow:Graph was finalized.
2019-09-18 17:16:24.874921: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
[horovod-job-example-volcanojob-master-0:00014] 1 more process has sent help message help-mpi-btl-base.txt / btl:no-nics
[horovod-job-example-volcanojob-master-0:00014] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into ./checkpoints/model.ckpt.
2019-09-18 17:16:32.814165: W tensorflow/core/framework/allocator.cc:122] Allocation of 67108864 exceeds 10% of system memory.
INFO:tensorflow:loss = 2.3109903, step = 1
INFO:tensorflow:loss = 2.2983603, step = 1
INFO:tensorflow:loss = 2.2829986, step = 11 (30.367 sec)
INFO:tensorflow:loss = 2.288348, step = 11 (30.368 sec)
INFO:tensorflow:loss = 2.2888207, step = 21 (30.632 sec)
INFO:tensorflow:loss = 2.290689, step = 21 (30.622 sec)
INFO:tensorflow:loss = 2.28215, step = 31 (30.747 sec)
INFO:tensorflow:loss = 2.2793612, step = 31 (30.755 sec)
```

예제 실행시 로그

**Comment by hyeongyun0916** [comment]
kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml
